### ISSUE TITLE
多次绑定域名提示错误

### ISSUE THREAD

**Issue by hwt88** [V2RaySSR/Trojan#14]
域名解析地址与本VPS IP地址不一致
本次安装失败，请确保域名解析正常

但是chinaz上面查询域名可以定位到ip的

**Comment by jinwyp** [comment]
要看vps的实际IP和域名解析的是否一样才行 ， 国内的解析不准， 用国外的试试  或直接ping 你的域名 看返回



可以试试我的脚本 https://github.com/jinwyp/one_click_script

**Comment by hwt88** [comment]
@jinwyp 果然可以解决我的问题。
